### ISSUE TITLE
[BUG] Lumen Unit Test - Strange Behaviors

### ISSUE THREAD

**Issue by hiraq** [laravel/lumen-framework#125]
Here my TestCase class:

```php
<?php

use Illuminate\Support\Facades\Artisan;
use App\Models\User;

class TestCase extends Laravel\Lumen\Testing\TestCase {

    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {
        return require __DIR__.'/../bootstrap/app.php';
    }

    public function setUp()
    {
        parent::setUp();
        $this->refreshApplication();
        Artisan::call('migrate');
    }

    public function tearDown()
    {
        Artisan::call('migrate:reset');
    }

}
```

And here my test scenario:

```php
<?php

use App\Models\User;
use App\Models\Observers\User as UserObserver;

class UsersControllerTest extends TestCase {

    public function testRegisterSuccess()
    {
        $params = [
            'email' => 'test@test.com',
            'password' => 'testing',
            'password_confirmation' => 'testing'
        ];

        $response = $this->call('POST', '/api/v1/users/register', $params);
        $json = json_decode($response->getContent()); 

        $this->assertResponseOk();
        
        /*
         * check and test json response
         */ 
        $this->assertTrue(isset($json->status));    
        $this->assertTrue(isset($json->data));    
        $this->assertEquals('success', $json->status); 
        $this->assertTrue(empty($json->data));

        /*
         * check and test database data
         */
        $user = User::where('email', 'test@test.com')->first();
        $this->assertTrue(!empty($user));
        $this->assertTrue(isset($user->email));
        $this->assertEquals('test@test.com', $user->email);        
    }

    public function testRegisterFailedEmailExists()
    {
        $this->generateUser('test@test.com', 'testing');
        
        $params = [
            'email' => 'test@test.com',
            'password' => 'testing',
            'password_confirmation' => 'testing'
        ];

        $response = $this->call('POST', '/api/v1/users/register', $params);
        $this->assertResponseStatus(400);

        $json = json_decode($response->getContent());
        
        $this->assertTrue(isset($json->status));
        $this->assertEquals('error', $json->status);

        $this->assertTrue(isset($json->message));
        $this->assertEquals('Fail to validate.', $json->message);
    }

    public function testRegisterEmptyParams()
    {
        $response = $this->call('POST', '/api/v1/users/register', []);
        $this->assertResponseStatus(400);

        $json = json_decode($response->getContent());
        
        $this->assertTrue(isset($json->status));
        $this->assertEquals('error', $json->status);

        $this->assertTrue(isset($json->message));
        $this->assertEquals('Fail to validate.', $json->message);
    }

    private function generateUser($email, $password)
    {
        User::observe(new UserObserver);
        $user = new User;
        $user->register($email, $password);
    }
}
```

When i run for each test like :

```
./vendor/bin/phpunit --filter testRegisterEmptyParams
```

It works fine, here my screenshot :
![lumen_test_empty_params](https://cloud.githubusercontent.com/assets/710299/7938241/bbcf1a56-096e-11e5-816c-5bcf4a93afe1.png)

but, when i run all tests :
![lumen_all_tests](https://cloud.githubusercontent.com/assets/710299/7938260/d5a4935c-096e-11e5-9d0e-8e6c201bcd97.png)

What happened here?

**Comment by hiraq** [comment]
And more strange things are:

![lumen_each_tests](https://cloud.githubusercontent.com/assets/710299/7938364/4ed1ec02-096f-11e5-84b4-71921ac54359.png)

If i run each test, it will be pass, but not if i run all tests..

What should i do ? I'm very confused here

**Comment by hiraq** [comment]
here my phpunit.xml :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/app.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_DATABASE" value="app_tests"/>
        <env name="DB_CONNECTION" value="mysql"/>
    </php>
</phpunit>
```

**Comment by hiraq** [comment]
it's like, there is a cache between test when i run all tests together, i dont know what or how, when i test request like :

```php
$response = $this->call('POST', '/api/v1/users/register', []);
```

it's same with previous test :

```php
$response = $this->call('POST', '/api/v1/users/register', $params);
```

Even i have put :
```php
$this->artisan('cache:clear')
```

in my `setUp` method and still not works

**Comment by hiraq** [comment]
Maybe like these :

#108 

and https://github.com/laravel/framework/issues/8547

**Comment by hiraq** [comment]
my users controller code:

```php
<?php namespace App\Http\Controllers;

use Request;
use Validator;
use App\Models\User;
use App\Models\Observers\User as UserObserver;

class UsersController extends Controller {

    public function postRegister()
    {
        $validate = Validator::make(Request::all(), [
            'email' => 'required|email|unique:users,email',
            'password' => 'required|confirmed',
            'password_confirmation' => 'required'
        ]);

        if($validate->fails()) {
            return $this->jsonable($validate->messages(), 'error', 400, 'Fail to validate.');
        } else {

            /*
             * listening to user model
             * on: creating, modify password, combine it with salt
             *
             * registering user data based on email and password
             */
            User::observe(new UserObserver); 
            $user = new User;
            $user->register(Request::input('email'), Request::input('password'));
            return $this->jsonable();
        }
    }

    public function postLogin()
    {

    }
}
```

**Comment by fesja** [comment]
It's happening the same to me. It's like the $server parameter of the Request object is not being refreshed:

```
<?php

class UserTest extends TestCase {

    /**
     * We correctly create a new user given the auth token.
     *
     * @return void
     */
    public function testCreate()
    {
        $auth_token = 'r56dc557c75';

        $serverParams = [
            'CONTENT_TYPE'      => 'application/json',
            'HTTP_X-Auth-Token' => $auth_token
        ];

        $response = $this->call('POST', '/v1/users',[],[],[], $serverParams);

        $this->assertResponseStatus(201, "The request is failing");

        $json = json_decode($response->getContent(), true);

        $this->assertArrayHasKey('data', $json, "The response has a wrong structure");
        $this->assertTrue(isset($json['data']['auth_token']), "It doesn't return the auth token");
        $this->assertEquals($json['data']['auth_token'], $auth_token, "The auth token is not the same");
    }

    /**
     * We correctly create a new user given the auth token.
     *
     * @return void
     */
    public function testCreateWithNoAuthToken()
    {
        $response = $this->call('POST', '/v1/users');

        $this->assertResponseStatus(400, "The request has passed through without auth token");
    }

}
```

**Comment by hiraq** [comment]
Ah finally, i thought that i'm the only one here @fesja , so what do yo do then to run your tests? until now i can't run all tests together, so i run my tests one by one, and it's very weird.  Just imagine if we have many tests.  

I'm still investigate about this issue, but still no clue, even i've explore into core codebase illuminate and laravel/lumen

**Comment by fesja** [comment]
It's my firs time doing tests without Lumen/Laravel so I'm going to wait until someone helps here. Yesterday I also looked at the code (following the $server parameter) but I couldn't found where it gets the content from the previous request.

**Comment by polesen** [comment]
Might be related to laravel/framework#8547 which have a fix now

**Comment by fesja** [comment]
@polesen @hiraq I've updated to the latest lumen-framework (not yet 5.1) and now it gives me this error https://laracasts.com/discuss/channels/lumen/problem-with-unit-test

Should I create an issue here?

**Comment by dwightwatson** [comment]
It appears to me as though this issue has been fixed in Lumen 5.1, can anyone else confirm this?

**Comment by hiraq** [comment]
@dwightwatson lumen 5.1? wow...well, ok, i'll try to update my apps

**Comment by dwightwatson** [comment]
Yeah, released this morning. All you need to do is change the Composer version constraint to `5.1.*` and update, nothing else like the Laravel 5.1 update required.

**Comment by levelfivehub** [comment]
I have the same problem.  

I have:
```
 "laravel/lumen-framework": "5.1.*",
```

But still receiving same issue as OP.

**Comment by nmfzone** [comment]
```
"laravel/lumen-framework": "5.3.*"
```

And this still happening :disappointed:

**Comment by gmansilla** [comment]
I'm using 5.2.9 and I'm experiencing the same issue.
