### ISSUE TITLE
$this->expectsJobs not working

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/lumen-framework#416]
Hi,

I've using this method when testing my previous Laravel projects. I have now a job-heavy Lumen app on which I would like to do the same. But for some reason I cannot get this to work. I then pulled out an fresh Lumen 5.2.6 app and did the following changes to make the most simplistic working example. I assume this should work.

routes.php

``` php
<?php

use App\Jobs\ExampleJob;

$app->get('/', function () use ($app) {
    dispatch(new ExampleJob);
});
```

ExampleTest.php

``` php
<?php

class ExampleTest extends TestCase
{
    public function testExample()
    {
        $this->expectsJobs('App\Jobs\ExampleJob');

        $this->get('/');
    }
}
```

Running phpunit:

```
vagrant@homestead:~/Code/lumen-test$ phpunit
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

E

Time: 3.54 seconds, Memory: 6.00MB

There was 1 error:

1) ExampleTest::testExample
Mockery\Exception\InvalidCountException: Method dispatch(object(Mockery\Matcher\Type)) from Mockery_0_Illuminate_Bus_Dispatcher should be called
 at least 1 times but called 0 times.

/home/vagrant/Code/lumen-test/vendor/mockery/mockery/library/Mockery/CountValidator/AtLeast.php:48
/home/vagrant/Code/lumen-test/vendor/mockery/mockery/library/Mockery/Expectation.php:297
/home/vagrant/Code/lumen-test/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:120
/home/vagrant/Code/lumen-test/vendor/mockery/mockery/library/Mockery/Container.php:297
/home/vagrant/Code/lumen-test/vendor/mockery/mockery/library/Mockery/Container.php:282
/home/vagrant/Code/lumen-test/vendor/mockery/mockery/library/Mockery.php:142
/home/vagrant/Code/lumen-test/vendor/laravel/lumen-framework/src/Testing/TestCase.php:107

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.

```

**Comment by GrahamCampbell** [comment]
What version of mockery please. Could you run `composer show -i.

**Comment by lasselehtinen** [comment]
Seems like mockery/mockery version 0.9.5. This comes from the version constraint ~9.0 in the [Lumen composer.json](https://github.com/laravel/lumen-framework/blob/5.2/composer.json#L49).

**Comment by GrahamCampbell** [comment]
Does it work if you hard code it to 0.9.4 please?

**Comment by lasselehtinen** [comment]
I tried from 0.9.4 to 0.9.0 and none of these worked. So it's leaning towards in issue with Lumen instead of mockery breaking BC on a patch version update?

**Comment by sagarrabadiya** [comment]
same problem, its not working for me as well.

**Comment by yuloh** [comment]
I'm pretty sure I figured out what is happening.

1. The expectsJobs method replaces the container binding with the mock.
2. When the dispatch helper function calls make on the app, the [make function](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L198) calls [registerBusBindings](https://github.com/laravel/lumen-framework/blob/5.2/src/Application.php#L251), which overwrites the mock binding with the real binding.
3. Since the mock binding is overwritten, the app gets the real thing and the method is never called on the mock.

I added a failing test [here](https://github.com/laravel/lumen-framework/compare/5.2...yuloh:overwrite-container-entries), that shows how the container overwrites bindings.  This will happen with any bindings listed in the availableBindings property of the application.

A hacky workaround is to resolve the object once out of the container before trying to register your binding.

**Comment by feeekkk** [comment]
Has anyone come up with a solution for this? I'm a little confused as to what this comment means:

> A hacky workaround is to resolve the object once out of the container before trying to register your binding.

**Comment by yuloh** [comment]
@feeekkk you need to do something like this:

    // Resolve the dispatcher even though we aren't using it.
    app('Illuminate\Contracts\Bus\Dispatcher');
// Now it will work correctly
    $this->expectsJobs($args);

**Comment by pedroplanel** [comment]
Hi there, this is solved? I'm facing the same problem with a simple test...

**Comment by PrinceDavis** [comment]
@pedroplanel move the call to $this->expectsJob(Job\Name); able the rest of your test logic

**Comment by mostafaabdelbaset** [comment]
I have the same problem, am using lumen 5.5

**Comment by yuloh** [comment]
@driesvints the test case I added is still failing in 5.7.  I don't believe this is fixed.

Simple example with psysh:

```
>>> $mock = Mockery::mock('Illuminate\Bus\Dispatcher');
=> Mockery_0_Illuminate_Bus_Dispatcher {#238}
>>> $app->instance('Illuminate\Contracts\Bus\Dispatcher', $mock);
=> Mockery_0_Illuminate_Bus_Dispatcher {#238}
>>> $app['Illuminate\Contracts\Bus\Dispatcher']
=> Illuminate\Bus\Dispatcher {#200}
```

**Comment by driesvints** [comment]
Okay, I'll have another look at a later time. Thanks for reporting.

**Comment by JacksonIV** [comment]
I can't seem to reproduce this anymore. the `ExpectsJobs` method is working fine for me.

**Comment by yuloh** [comment]
Oh, it looks like `expectsJobs` specifically was fixed by 16a452a, but the underlying problem of container bindings being overwritten still exists.  I can open a more specific issue for that.

**Comment by mostafaabdelbaset** [comment]
With me, It's working with dispatch( ) but not working with event( )

**Comment by yuloh** [comment]
@mostafaabdelbaset until this is fixed you can use the same workaround from 16a452a.  This should work:

```php
unset($this->app->availableBindings['events']);
unset($this->app->availableBindings['Illuminate\Contracts\Events\Dispatcher']);
$this->expectsEvents('SomeEvent');
```

**Comment by yuloh** [comment]
This should work correctly now for `expectsJobs`, `expectsEvents`, or any other use case that requires overwriting an available binding.

**Comment by driesvints** [comment]
Thanks @yuloh!
